services:
  postgres-db:
    image: postgres:16
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  weather-api:
    build: .
    depends_on:
      - postgres-db
    ports:
      - '8080:8080'
    environment:
      DATABASE_HOST: host.docker.internal #You can change
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE: ${DATABASE}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_LOGIN: ${MAIL_LOGIN}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_FROM: ${MAIL_FROM}
      API_KEY: ${API_KEY}
    command: npm run start:prod

volumes:
  postgres-data:
